

#ifndef WALLET_WALLET_DEFINITIONS_H
#define WALLET_WALLET_DEFINITIONS_H

// Ed25519 definitions
#define WALLET_WALLET_DEFINITIONS_ED25519_PRIVATE_KEY_LENGTH 64 // Private Key Length
#define WALLET_WALLET_DEFINITIONS_ED25519_PUBLIC_KEY_LENGTH 32 // Public Key Length
#define WALLET_WALLET_DEFINITIONS_ED25519_SIGNATURE_LENGTH 64 // Signature Length

// Wallet Related

// Wallet Connections Information
#define WALLET_WALLET_DEFINITIONS_WALLET_CONNECTIONS_INFORMATION_COMMUNICATION_CONNECTIONS_COUNT_LENGTH 2

// When not specify path, this is used as path
#define WALLET_WALLET_DEFINITIONS_DEFAULT_SETTINGS_PATH "./wallet_settings"

// Length of not need data for save() 
// -> signature variable ( WALLET_WALLET_DEFINITIONS_ED25519_SIGNATURE_LENGTH )
#define WALLET_WALLET_DEFINITIONS_NOT_NEED_DATA_LENGTH \
    WALLET_WALLET_DEFINITIONS_ED25519_SIGNATURE_LENGTH

#endif