

#ifndef TYPES_BLOCK_PART_DEFINITIONS_H
#define TYPES_BLOCK_PART_DEFINITIONS_H

// Block Part params lengths 
#define TYPES_BLOCK_PART_TRANSACTION_COUNT_LENGTH 4
#define TYPES_BLOCK_PART_PREVIOUS_HASH_LENGTH 64
#define TYPES_BLOCK_PART_HASH_LENGTH 64



#endif