

#ifndef TYPES_TRANSACTION_DEFINITIONS_H
#define TYPES_TRANSACTION_DEFINITIONS_H

#include "wallet_definitions.h" // Ed25519 info

// Transaction params length
#define TYPES_TRANSACTION_TRANSACTION_AMOUNT_LENGTH 8
#define TYPES_TRANSACTION_TRANSACTION_FEE_LENGTH 8
#define TYPES_TRANSACTION_TRANSACTION_NONCE_LENGTH 8
#define TYPES_TRANSACTION_TRANSACTION_FROM_BALANCE_LENGTH 8
#define TYPES_TRANSACTION_TRANSACTION_TO_BALANCE_LENGTH 8

// Transaction length
#define TRANSACTION_LENGTH \
    WALLET_WALLET_DEFINITIONS_ED25519_SIGNATURE_LENGTH + WALLET_WALLET_DEFINITIONS_ED25519_PUBLIC_KEY_LENGTH + WALLET_WALLET_DEFINITIONS_ED25519_PUBLIC_KEY_LENGTH + \
        TYPES_TRANSACTION_TRANSACTION_AMOUNT_LENGTH + TYPES_TRANSACTION_TRANSACTION_FEE_LENGTH + TYPES_TRANSACTION_TRANSACTION_NONCE_LENGTH + TYPES_TRANSACTION_TRANSACTION_FROM_BALANCE_LENGTH \
            TYPES_TRANSACTION_TRANSACTION_TO_BALANCE_LENGTH

// Transaction sign data length 
#define TRANSACTION_SIGN_DATA_LENGTH \
    WALLET_WALLET_DEFINITIONS_ED25519_PUBLIC_KEY_LENGTH + WALLET_WALLET_DEFINITIONS_ED25519_PUBLIC_KEY_LENGTH + \
        TYPES_TRANSACTION_TRANSACTION_AMOUNT_LENGTH + TYPES_TRANSACTION_TRANSACTION_FEE_LENGTH + TYPES_TRANSACTION_TRANSACTION_NONCE_LENGTH

// Transaction Propagation length
#define TRANSACTION_PROPAGATION_LENGTH \ 
    TRANSACTION_SIGN_DATA_LENGTH + WALLET_WALLET_DEFINITIONS_ED25519_SIGNATURE_LENGTH

#endif