
#ifndef P2P_SOCKET_CONNECTION_DEFINITIONS_H
#define P2P_SOCKET_CONNECTION_DEFINITIONS_H

// Internet protocol version
#define P2P_SOCKET_CONNECTION_VERSION_IPV4 4
#define P2P_SOCKET_CONNECTION_VERSION_IPV6 6

// Connection status 
#define P2P_SOCKET_CONNECTION_STATUS_NOT_CONNECTED 0 // No action
#define P2P_SOCKET_CONNECTION_STATUS_CONNECTED 1 // Connected to end point
#define P2P_SOCKET_CONNECTION_STATUS_SERVER 2 // Server with end point

// Connection Params lengths
#define P2P_SOCKET_CONNECTION_VERSION_LENGTH 1

#endif