

#ifndef P2P_SOCKET_END_POINT_IPV4_DEFINITIONS_H
#define P2P_SOCKET_END_POINT_IPV4_DEFINITIONS_H

// End Point

#define P2P_SOCKET_END_POINT_IPV4_ADDRESS_LENGTH 4
#define P2P_SOCKET_END_POINT_IPV4_PORT_LENGTH 2

#endif