

#ifndef P2P_SOCKET_PACKET_DEFINITIONS_H
#define P2P_SOCKET_PACKET_DEFINITIONS_H

// Packet params length
#define P2P_SOCKET_PACKET_DEFINITIONS_PROTOCOL_ID_LENGTH 1
#define P2P_SOCKET_PACKET_DEFINITIONS_SIZE_LENGTH 8

#endif